set serveroutput on
DECLARE
  ID VARCHAR2(200);
  STMT VARCHAR2(200);
  BINDINGS VARCHAR2(200);
  NO_NEWLINE_STMT VARCHAR2(200);
  NO_NEWLINE_BINDINGS VARCHAR2(200);
  NEWLINE_ONLY_STMT VARCHAR2(200);
  NEWLINE_ONLY_BINDINGS VARCHAR2(200);
  MAXIMUM_LINE_SEGMENT_LENGTH NUMBER;
  ALLOW_REPLACE NUMBER;
  FROM_STDOUT NUMBER;
  FROM_STDERR NUMBER;
  INCLUDE_NEWLINES NUMBER;
  EAGER NUMBER;
  v_Return VARCHAR2(200);
BEGIN
  /*
accept_from_java
ID VARCHAR2, TEXT VARCHAR2, LENGTH NUMBER, LINENO NUMBER, SEGNO NUMBER, NL NUMBER, and ERROUT NUMBER
*/
  STMT := 'declare l logger :=logmanager.getlogger(:a); begin l.debug(:b); end;';
  BINDINGS := 'ID TEXT';
  --BINDINGS := 'TEXT'; -- ID, TEXT, LENGTH, LINENO, SEGNO, NL, and ERROUT
  NO_NEWLINE_STMT := NULL;
  NO_NEWLINE_BINDINGS := NULL;
  NEWLINE_ONLY_STMT := NULL;
  NEWLINE_ONLY_BINDINGS := NULL;
  MAXIMUM_LINE_SEGMENT_LENGTH := 0;
  ALLOW_REPLACE := 0;
  INCLUDE_NEWLINES := 0;
  EAGER := 0;

  ID := 'JAVA.STDOUT'; 
  FROM_STDOUT := 1;
  FROM_STDERR := 0;

  v_Return := SYS.DBMS_JAVA.SET_OUTPUT_TO_SQL(
    ID => ID,
    STMT => STMT,
    BINDINGS => BINDINGS,
    NO_NEWLINE_STMT => NO_NEWLINE_STMT,
    NO_NEWLINE_BINDINGS => NO_NEWLINE_BINDINGS,
    NEWLINE_ONLY_STMT => NEWLINE_ONLY_STMT,
    NEWLINE_ONLY_BINDINGS => NEWLINE_ONLY_BINDINGS,
    MAXIMUM_LINE_SEGMENT_LENGTH => MAXIMUM_LINE_SEGMENT_LENGTH,
    ALLOW_REPLACE => ALLOW_REPLACE,
    FROM_STDOUT => FROM_STDOUT,
    FROM_STDERR => FROM_STDERR,
    INCLUDE_NEWLINES => INCLUDE_NEWLINES,
    EAGER => EAGER
  );
DBMS_OUTPUT.PUT_LINE('v_Return = ' || v_Return);

  ID := 'JAVA.STDERR'; 
  FROM_STDOUT := 0;
  FROM_STDERR := 1;
  v_Return := SYS.DBMS_JAVA.SET_OUTPUT_TO_SQL(
    ID => ID,
    STMT => STMT,
    BINDINGS => BINDINGS,
    NO_NEWLINE_STMT => NO_NEWLINE_STMT,
    NO_NEWLINE_BINDINGS => NO_NEWLINE_BINDINGS,
    NEWLINE_ONLY_STMT => NEWLINE_ONLY_STMT,
    NEWLINE_ONLY_BINDINGS => NEWLINE_ONLY_BINDINGS,
    MAXIMUM_LINE_SEGMENT_LENGTH => MAXIMUM_LINE_SEGMENT_LENGTH,
    ALLOW_REPLACE => ALLOW_REPLACE,
    FROM_STDOUT => FROM_STDOUT,
    FROM_STDERR => FROM_STDERR,
    INCLUDE_NEWLINES => INCLUDE_NEWLINES,
    EAGER => EAGER
  );
DBMS_OUTPUT.PUT_LINE('v_Return = ' || v_Return);
END;
/

